"""

Django settings for simplisolve_us project.



Generated by 'django-admin startproject' using Django 4.1.5.



For more information on this file, see

https://docs.djangoproject.com/en/4.1/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/4.1/ref/settings/

"""


from pathlib import Path

import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-xphu!8op(q!_p$$dem8_eqx5b@hc-vamrss^7sjs8+83%1c_v3'


# SECURITY WARNING: don't run with debug turned on in production!


# Following are to run in admin.simplisove.us

DEBUG = True

ALLOWED_HOSTS = []


# # Following are to run in localhost

# DEBUG =True

# ALLOWED_HOSTS = []


# Application definition


INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'simplisolve_app',

    'ipware',
    'captcha',



]


MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    

]

LOGIN_URL = '/login/'

ROOT_URLCONF = 'simplisolve_us.urls'


TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
                'simplisolve_app.context_processors.profile_name',

            ],

        },

    },

]


WSGI_APPLICATION = 'simplisolve_us.wsgi.application'


# Database

# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}


# Password validation

# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]


# Internationalization

# https://docs.djangoproject.com/en/4.1/topics/i18n/


LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'UTC'


USE_I18N = True


USE_TZ = True


# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = 'static/'

STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'simplisolve_app/static'),

]

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Default primary key field type

# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# EMAIL_HOST = 'smtp.gmail.com'

# EMAIL_PORT = 465

# EMAIL_USE_TLS = False  # Disable TLS since you're using SSL

# EMAIL_USE_SSL = True # Use port 587 for TLS  # Use TLS encryption

# EMAIL_HOST_USER ='dpkchoudhary103@gmail.com'

# EMAIL_HOST_PASSWORD ='kscibvcsrzveflcg'

RECAPTCHA_PUBLIC_KEY = "6LcOJpcoAAAAAN-RU41hpBkrZkuLgirz9rOpjxdq"
RECAPTCHA_PRIVATE_KEY = "6LcOJpcoAAAAAGArE5xvtp39J_d6UHj4R7qehRdD"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'  # Zoho SMTP server
EMAIL_PORT = 587  # Use port 587 for TLS
EMAIL_USE_TLS = True  # Enable TLS encryption
EMAIL_USE_SSL = False  # Disable SSL
EMAIL_HOST_USER = 'support@simplisolve.us'  # Your Zoho email address
EMAIL_HOST_PASSWORD = 'T&jA%fzYw7v%ga'  # Your Zoho email password

# SECOND_EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# SECOND_EMAIL_HOST = 'smtp.zoho.com'
# SECOND_EMAIL_PORT = 587
# SECOND_EMAIL_USE_TLS = True
# SECOND_EMAIL_USE_SSL = False
# SECOND_EMAIL_HOST_USER = 'recruitment@simplisolve.us'
# SECOND_EMAIL_HOST_PASSWORD = '4wHE4NJ3g2z$j4'

SECOND_EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SECOND_EMAIL_HOST = 'smtp.gmail.com'
SECOND_EMAIL_PORT = 465
SECOND_EMAIL_USE_TLS = False
SECOND_EMAIL_USE_SSL = True
SECOND_EMAIL_HOST_USER = 'dpkchoudhary103@gmail.com'
SECOND_EMAIL_HOST_PASSWORD = 'kscibvcsrzveflcg'


MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# settings.py

# Set session expiration to 1 hour
SESSION_COOKIE_AGE = 1800  # 1 hour in seconds
