# Generated by Django 5.0 on 2023-12-20 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simplisolve_app", "0003_save_score_data_scientist_technical"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Save_score_data_scientist_technical",
            new_name="SaveScoreDataScientistTechnical",
        ),
    ]
